# Netlify configuration for ElevenLabs webhook integration

[build]
  command = "npx vite build"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"
  publish = "dist"

# Edge Function configuration
[[edge_functions]]
  function = "elevenlabs-webhook"
  path = "/api/elevenlabs-webhook"

# Build environment
[build.environment]
  NODE_VERSION = "18"

# Environment variables for different contexts
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "staging"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Headers for security
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects for API endpoints
[[redirects]]
  from = "/webhook/elevenlabs"
  to = "/api/elevenlabs-webhook"
  status = 301

[[redirects]]
  from = "/api/webhook/elevenlabs"
  to = "/api/elevenlabs-webhook"
  status = 301